ALTER TABLE IF EXISTS paper_trading_settings
    ADD COLUMN IF NOT EXISTS paper_trading_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS require_candle_close_beyond_line BOOLEAN,
    ADD COLUMN IF NOT EXISTS target_mode VARCHAR(40),
    ADD COLUMN IF NOT EXISTS fallback_risk_reward_ratio DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS use_nearest_daily_swing_target BOOLEAN,
    ADD COLUMN IF NOT EXISTS minimum_reward_risk_ratio DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS order_type VARCHAR(20),
    ADD COLUMN IF NOT EXISTS product_type VARCHAR(20),
    ADD COLUMN IF NOT EXISTS reentry_cooldown_minutes INTEGER,
    ADD COLUMN IF NOT EXISTS allow_repeat_entry_same_line BOOLEAN,
    ADD COLUMN IF NOT EXISTS max_quantity_per_order INTEGER,
    ADD COLUMN IF NOT EXISTS skip_zero_previous_volume BOOLEAN,
    ADD COLUMN IF NOT EXISTS minimum_price DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS maximum_price DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS allowed_exchanges JSONB,
    ADD COLUMN IF NOT EXISTS max_open_positions INTEGER,
    ADD COLUMN IF NOT EXISTS max_loss_per_symbol_per_day DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS block_new_trades_after_max_daily_loss BOOLEAN,
    ADD COLUMN IF NOT EXISTS no_trade_after_time VARCHAR(10),
    ADD COLUMN IF NOT EXISTS market_hours_guard BOOLEAN,
    ADD COLUMN IF NOT EXISTS exchange_charges_estimate DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS use_cost_adjusted_pnl BOOLEAN,
    ADD COLUMN IF NOT EXISTS enable_confidence_filter BOOLEAN,
    ADD COLUMN IF NOT EXISTS minimum_confidence_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS confidence_source VARCHAR(30),
    ADD COLUMN IF NOT EXISTS allow_low_confidence_paper_trades_only BOOLEAN,
    ADD COLUMN IF NOT EXISTS block_live_trades_below_confidence_threshold BOOLEAN;

UPDATE paper_trading_settings
SET
    paper_trading_enabled = COALESCE(paper_trading_enabled, TRUE),
    require_candle_close_beyond_line = COALESCE(require_candle_close_beyond_line, TRUE),
    target_mode = COALESCE(target_mode, 'NEAREST_DAILY_SWING'),
    fallback_risk_reward_ratio = COALESCE(fallback_risk_reward_ratio, 2.0),
    use_nearest_daily_swing_target = COALESCE(use_nearest_daily_swing_target, TRUE),
    minimum_reward_risk_ratio = COALESCE(minimum_reward_risk_ratio, 1.0),
    order_type = COALESCE(order_type, 'LIMIT'),
    product_type = COALESCE(product_type, 'MIS'),
    reentry_cooldown_minutes = COALESCE(reentry_cooldown_minutes, 0),
    allow_repeat_entry_same_line = COALESCE(allow_repeat_entry_same_line, FALSE),
    skip_zero_previous_volume = COALESCE(skip_zero_previous_volume, TRUE),
    allowed_exchanges = COALESCE(allowed_exchanges, '["NSE","BSE"]'::jsonb),
    max_open_positions = COALESCE(max_open_positions, 3),
    max_loss_per_symbol_per_day = COALESCE(max_loss_per_symbol_per_day, 2500.0),
    block_new_trades_after_max_daily_loss = COALESCE(block_new_trades_after_max_daily_loss, TRUE),
    no_trade_after_time = COALESCE(no_trade_after_time, '15:00'),
    market_hours_guard = COALESCE(market_hours_guard, TRUE),
    exchange_charges_estimate = COALESCE(exchange_charges_estimate, 0.0),
    use_cost_adjusted_pnl = COALESCE(use_cost_adjusted_pnl, TRUE),
    enable_confidence_filter = COALESCE(enable_confidence_filter, FALSE),
    minimum_confidence_score = COALESCE(minimum_confidence_score, 0.6),
    confidence_source = COALESCE(confidence_source, 'RULES_ONLY'),
    allow_low_confidence_paper_trades_only = COALESCE(allow_low_confidence_paper_trades_only, TRUE),
    block_live_trades_below_confidence_threshold = COALESCE(block_live_trades_below_confidence_threshold, TRUE);

ALTER TABLE paper_trading_settings
    ALTER COLUMN paper_trading_enabled SET DEFAULT TRUE,
    ALTER COLUMN paper_trading_enabled SET NOT NULL,
    ALTER COLUMN require_candle_close_beyond_line SET DEFAULT TRUE,
    ALTER COLUMN require_candle_close_beyond_line SET NOT NULL,
    ALTER COLUMN target_mode SET DEFAULT 'NEAREST_DAILY_SWING',
    ALTER COLUMN target_mode SET NOT NULL,
    ALTER COLUMN fallback_risk_reward_ratio SET DEFAULT 2.0,
    ALTER COLUMN fallback_risk_reward_ratio SET NOT NULL,
    ALTER COLUMN use_nearest_daily_swing_target SET DEFAULT TRUE,
    ALTER COLUMN use_nearest_daily_swing_target SET NOT NULL,
    ALTER COLUMN minimum_reward_risk_ratio SET DEFAULT 1.0,
    ALTER COLUMN minimum_reward_risk_ratio SET NOT NULL,
    ALTER COLUMN order_type SET DEFAULT 'LIMIT',
    ALTER COLUMN order_type SET NOT NULL,
    ALTER COLUMN product_type SET DEFAULT 'MIS',
    ALTER COLUMN product_type SET NOT NULL,
    ALTER COLUMN reentry_cooldown_minutes SET DEFAULT 0,
    ALTER COLUMN reentry_cooldown_minutes SET NOT NULL,
    ALTER COLUMN allow_repeat_entry_same_line SET DEFAULT FALSE,
    ALTER COLUMN allow_repeat_entry_same_line SET NOT NULL,
    ALTER COLUMN skip_zero_previous_volume SET DEFAULT TRUE,
    ALTER COLUMN skip_zero_previous_volume SET NOT NULL,
    ALTER COLUMN allowed_exchanges SET DEFAULT '["NSE","BSE"]'::jsonb,
    ALTER COLUMN allowed_exchanges SET NOT NULL,
    ALTER COLUMN max_open_positions SET DEFAULT 3,
    ALTER COLUMN max_open_positions SET NOT NULL,
    ALTER COLUMN max_loss_per_symbol_per_day SET DEFAULT 2500.0,
    ALTER COLUMN max_loss_per_symbol_per_day SET NOT NULL,
    ALTER COLUMN block_new_trades_after_max_daily_loss SET DEFAULT TRUE,
    ALTER COLUMN block_new_trades_after_max_daily_loss SET NOT NULL,
    ALTER COLUMN market_hours_guard SET DEFAULT TRUE,
    ALTER COLUMN market_hours_guard SET NOT NULL,
    ALTER COLUMN exchange_charges_estimate SET DEFAULT 0.0,
    ALTER COLUMN exchange_charges_estimate SET NOT NULL,
    ALTER COLUMN use_cost_adjusted_pnl SET DEFAULT TRUE,
    ALTER COLUMN use_cost_adjusted_pnl SET NOT NULL,
    ALTER COLUMN enable_confidence_filter SET DEFAULT FALSE,
    ALTER COLUMN enable_confidence_filter SET NOT NULL,
    ALTER COLUMN minimum_confidence_score SET DEFAULT 0.6,
    ALTER COLUMN minimum_confidence_score SET NOT NULL,
    ALTER COLUMN confidence_source SET DEFAULT 'RULES_ONLY',
    ALTER COLUMN confidence_source SET NOT NULL,
    ALTER COLUMN allow_low_confidence_paper_trades_only SET DEFAULT TRUE,
    ALTER COLUMN allow_low_confidence_paper_trades_only SET NOT NULL,
    ALTER COLUMN block_live_trades_below_confidence_threshold SET DEFAULT TRUE,
    ALTER COLUMN block_live_trades_below_confidence_threshold SET NOT NULL;
